import Head from 'next/head';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useEffect, useState } from 'react';
import { CharactersCard } from '../../components/characters-card';

export default function CharacterProfile() {
  const router = useRouter();
  const [data, setData] = useState({});
  const [characters, setCharacters] = useState([]);

  useEffect(() => {
    router.query.pid &&
      fetch(`https://rickandmortyapi.com/api/episode/${router.query.pid}`)
        .then((res) => res.json())
        .then((data) => {
          console.log(data);
          setData(data);
        });
  }, [router.query]);

  useEffect(() => {
    if (data !== {}) {
      data.characters?.map((character) => {
        const characterId = character.split('/character/')[1];

        fetch(`https://rickandmortyapi.com/api/character/${characterId}`)
          .then((res) => res.json())
          .then((data) => {
            setCharacters((prev) => [...prev, data]);
          });
      });
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>{data.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main style={{ backgroundColor: 'white' }}>
        <div style={{ display: 'flex', flexDirection: 'row', justifyContent: 'center', alingItems: 'center', gap: "10em" }}>
          <h1 style={{ color: "black" }}>{data.name}</h1>
          <div style={{}}>
            <h3 style={{ color: "black" }}>Episode</h3>
            <h2 style={{ color: "black" }}>
              {new Date(data.air_date).toLocaleDateString('en-US', {
                month: 'long',
                day: 'numeric',
                year: 'numeric',
              })}
            </h2>
          </div>

          <div style={{}}>
            <h3 style={{ margin: "1em", color: "black" }}>Date</h3>
            <h2 style={{ margin: "1em", color: "black" }}>{data.episode}</h2>
          </div>
        </div>

        <h3 style={{ color: "black" }}>Cast</h3>
        <div
          style={{
            display: 'flex',
            flexDirection: 'column',
            alignItems: 'center',
            gap: '10px',
            display: 'grid',
            gridTemplateColumns: 'repeat(4, 1fr)',
            gap: '2em',
          }}
        >
          {characters?.map((character, index) => {
            return (
              <Link href={`/characters/${character.id}`} key={index}>
                <CharactersCard
                  name={character.name}
                  species={character.species}
                  image={character.image}
                />
              </Link>
            );
          })}
        </div >
      </main >
    </>
  );
}